/**
 * Pattern metadata for the website. GENERATED FILE — do not edit by hand.
 *
 * Source of truth: per-entry metadata.json files under patterns/, primitives/,
 * and modifiers/, aggregated via meta/validate-metadata.js into
 * patterns-catalog.yaml. This TypeScript module is regenerated by
 * meta/generate-website-data.js.
 *
 * To add or modify an entry:
 *   1. Edit the relevant metadata.json (and any tier .md files) under
 *      patterns/, primitives/, or modifiers/.
 *   2. Run: node meta/validate-metadata.js --emit patterns-catalog.yaml
 *   3. Run: node meta/generate-website-data.js
 *   4. Commit all three changes (metadata.json, patterns-catalog.yaml, and
 *      this generated TS file).
 *
 * See meta/HOW_TO_ADD_AN_ENTRY.md for the full contributor walkthrough.
 */

export type Complexity = 'Beginner' | 'Intermediate' | 'Advanced';
export type Category = 'workflow' | 'agent' | 'primitive' | 'modifier';
export type Kind = 'pattern' | 'primitive' | 'modifier';

export interface PatternMeta {
  id: string;
  name: string;
  slug: string;
  description: string;
  complexity: Complexity;
  category: Category;
  /** Which cohort this entry belongs to — drives website routing. */
  kind: Kind;
  /** For agent patterns: the workflow(s) this evolves from */
  evolvesFrom?: string[];
  /** Agent patterns that evolve FROM this workflow (for workflow patterns) */
  evolvesInto?: string[];
  /** For modifiers: which patterns this can be layered on (or ['any']) */
  appliesTo?: string[];
}

// ---------------------------------------------------------------------------
// Workflows (kept as a named subset of patterns for backward compat — same
// entries also appear in the unified patterns/ catalog directory).
// ---------------------------------------------------------------------------

export const WORKFLOWS: PatternMeta[] = [
  {
    id: 'evaluator-optimizer',
    name: 'Evaluator-Optimizer',
    slug: 'evaluator-optimizer',
    description: 'Generate-evaluate feedback loop that iteratively improves output.',
    complexity: 'Intermediate',
    category: 'workflow',
    kind: 'pattern',
    evolvesInto: ['reflection'],
  },
  {
    id: 'orchestrator-worker',
    name: 'Orchestrator-Worker',
    slug: 'orchestrator-worker',
    description: 'LLM decomposes a task and delegates to specialized workers.',
    complexity: 'Intermediate',
    category: 'workflow',
    kind: 'pattern',
    evolvesInto: ['plan_and_execute', 'multi_agent'],
  },
  {
    id: 'parallel-calls',
    name: 'Parallel Calls',
    slug: 'parallel-calls',
    description: 'Concurrent LLM calls on independent inputs, aggregated at the end.',
    complexity: 'Beginner',
    category: 'workflow',
    kind: 'pattern',
    evolvesInto: ['rag', 'routing'],
  },
  {
    id: 'prompt-chaining',
    name: 'Prompt Chaining',
    slug: 'prompt-chaining',
    description: 'Sequential LLM calls with validation gates between steps.',
    complexity: 'Beginner',
    category: 'workflow',
    kind: 'pattern',
    evolvesInto: ['react', 'tool_use', 'memory'],
  },
];

// ---------------------------------------------------------------------------
// Agent patterns — LLM-controlled flow shapes.
// ---------------------------------------------------------------------------

export const AGENT_PATTERNS: PatternMeta[] = [
  {
    id: 'agentic_rag',
    name: 'Agentic RAG',
    slug: 'agentic-rag',
    description: 'RAG where the agent plans retrievals, decomposes queries, routes across sources, reflects on sufficiency, and enforces citation-bound answers.',
    complexity: 'Advanced',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['rag', 'plan_and_execute'],
  },
  {
    id: 'event_driven',
    name: 'Event-Driven',
    slug: 'event-driven',
    description: 'Agents triggered by queue or stream events rather than HTTP requests.',
    complexity: 'Advanced',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['tool_use'],
  },
  {
    id: 'long_horizon',
    name: 'Long-Horizon',
    slug: 'long-horizon',
    description: 'Multi-session agent tasks that span hours to weeks; checkpoint-and-resume across crashes, deploys, and external waits.',
    complexity: 'Advanced',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['saga', 'event_driven'],
  },
  {
    id: 'multi_agent',
    name: 'Multi-Agent',
    slug: 'multi-agent',
    description: 'Supervisor-worker delegation across multiple autonomous agents.',
    complexity: 'Advanced',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['orchestrator-worker', 'routing'],
  },
  {
    id: 'plan_and_execute',
    name: 'Plan & Execute',
    slug: 'plan-and-execute',
    description: 'LLM creates a full plan upfront, then executes each step sequentially.',
    complexity: 'Intermediate',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['orchestrator-worker'],
  },
  {
    id: 'rag',
    name: 'RAG',
    slug: 'rag',
    description: 'Retrieval-augmented generation: retrieve relevant context before generating.',
    complexity: 'Intermediate',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['parallel-calls'],
  },
  {
    id: 'react',
    name: 'ReAct',
    slug: 'react',
    description: 'Reason-act loop: the LLM reasons, calls a tool, observes, and repeats until done.',
    complexity: 'Intermediate',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['prompt-chaining'],
  },
  {
    id: 'reflection',
    name: 'Reflection',
    slug: 'reflection',
    description: 'LLM critiques its own output and self-improves through structured feedback.',
    complexity: 'Intermediate',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['evaluator-optimizer'],
  },
  {
    id: 'routing',
    name: 'Routing',
    slug: 'routing',
    description: 'Intent classification dispatches inputs to specialized handlers.',
    complexity: 'Beginner',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['parallel-calls'],
  },
  {
    id: 'saga',
    name: 'Saga',
    slug: 'saga',
    description: 'Long-running, multi-step business processes that need compensation when an intermediate step fails.',
    complexity: 'Advanced',
    category: 'agent',
    kind: 'pattern',
    evolvesFrom: ['tool_use', 'prompt-chaining'],
  },
];

// ---------------------------------------------------------------------------
// Primitives — building blocks the agent uses. Orthogonal to patterns.
// ---------------------------------------------------------------------------

export const PRIMITIVES: PatternMeta[] = [
  {
    id: 'memory',
    name: 'Memory',
    slug: 'memory',
    description: 'Persistent state across sessions: short-term, long-term, and semantic memory.',
    complexity: 'Intermediate',
    category: 'primitive',
    kind: 'primitive',
    evolvesFrom: ['prompt-chaining'],
  },
  {
    id: 'skills',
    name: 'Skills',
    slug: 'skills',
    description: 'File-based, agent-discovered procedural modules. Cheap to ship many; loaded on demand at runtime.',
    complexity: 'Intermediate',
    category: 'primitive',
    kind: 'primitive',
    evolvesFrom: ['tool_use'],
  },
  {
    id: 'sub_agents',
    name: 'Sub-agents',
    slug: 'sub-agents',
    description: 'Named, role-scoped agent instances spawned by a parent for delimited tasks; each has its own context window, tool grants, and (optionally) model.',
    complexity: 'Intermediate',
    category: 'primitive',
    kind: 'primitive',
    evolvesFrom: ['tool_use'],
  },
  {
    id: 'tool_use',
    name: 'Tool Use',
    slug: 'tool-use',
    description: 'Structured function calling with schema-validated tool dispatch.',
    complexity: 'Beginner',
    category: 'primitive',
    kind: 'primitive',
    evolvesFrom: ['prompt-chaining'],
  },
];

// ---------------------------------------------------------------------------
// Modifiers — transformations layered on a pattern.
// ---------------------------------------------------------------------------

export const MODIFIERS: PatternMeta[] = [
  {
    id: 'guardrails',
    name: 'Guardrails',
    slug: 'guardrails',
    description: 'Layered input / tool / output policy checks plus a dual-LLM split that breaks the indirect-prompt-injection path.',
    complexity: 'Advanced',
    category: 'modifier',
    kind: 'modifier',
    evolvesFrom: ['tool_use'],
    appliesTo: ['any'],
  },
  {
    id: 'human_in_the_loop',
    name: 'Human in the Loop',
    slug: 'human-in-the-loop',
    description: 'Agent proposes an action; a human approves, denies, or modifies before the action commits.',
    complexity: 'Intermediate',
    category: 'modifier',
    kind: 'modifier',
    evolvesFrom: ['tool_use'],
  },
];

// ---------------------------------------------------------------------------
// Lookups (any of patterns + primitives + modifiers).
// ---------------------------------------------------------------------------

export const ALL_PATTERNS: PatternMeta[] = [
  ...WORKFLOWS,
  ...AGENT_PATTERNS,
  ...PRIMITIVES,
  ...MODIFIERS,
];

export function getPatternById(id: string): PatternMeta | undefined {
  return ALL_PATTERNS.find((p) => p.id === id);
}

export function getWorkflowById(id: string): PatternMeta | undefined {
  return WORKFLOWS.find((p) => p.id === id);
}

export function getAgentPatternById(id: string): PatternMeta | undefined {
  return AGENT_PATTERNS.find((p) => p.id === id);
}

export function getPrimitiveById(id: string): PatternMeta | undefined {
  return PRIMITIVES.find((p) => p.id === id);
}

export function getModifierById(id: string): PatternMeta | undefined {
  return MODIFIERS.find((p) => p.id === id);
}

/** Evolution edges: workflow → agent patterns (only) */
export const EVOLUTION_EDGES = AGENT_PATTERNS.flatMap((ap) =>
  (ap.evolvesFrom ?? []).map((wfId) => ({ source: wfId, target: ap.id })),
);

/** Comparison data for /compare/ */
export interface PatternComparison {
  id: string;
  name: string;
  category: Category;
  complexity: Complexity;
  latency: 'Low' | 'Medium' | 'High' | 'Variable';
  cost: 'Low' | 'Medium' | 'High' | 'Variable';
  bestFor: string;
  requires: string[];
  composableWith: string[];
}

export const PATTERN_COMPARISONS: PatternComparison[] = [
  {
    id: 'agentic_rag',
    name: 'Agentic RAG',
    category: 'agent',
    complexity: 'Advanced',
    latency: 'High',
    cost: 'Medium',
    bestFor: 'Compound or multi-source questions where grounding and citations matter',
    requires: ['retrieval', 'source-registry', 'citation-tracker'],
    composableWith: ['reflection', 'react', 'sub_agents', 'routing', 'memory'],
  },
  {
    id: 'evaluator-optimizer',
    name: 'Evaluator-Optimizer',
    category: 'workflow',
    complexity: 'Intermediate',
    latency: 'High',
    cost: 'High',
    bestFor: 'Quality-sensitive outputs needing iteration',
    requires: [],
    composableWith: ['prompt-chaining', 'rag'],
  },
  {
    id: 'event_driven',
    name: 'Event-Driven',
    category: 'agent',
    complexity: 'Advanced',
    latency: 'Medium',
    cost: 'Medium',
    bestFor: 'Async reactive systems on a queue or stream',
    requires: ['tools', 'event-source', 'idempotency-store'],
    composableWith: ['multi_agent', 'routing', 'memory'],
  },
  {
    id: 'long_horizon',
    name: 'Long-Horizon',
    category: 'agent',
    complexity: 'Advanced',
    latency: 'High',
    cost: 'High',
    bestFor: 'Tasks that span hours to weeks with checkpoint-and-resume across deploys',
    requires: ['checkpoint-store', 'event-log', 'idempotency', 'tick-worker'],
    composableWith: ['sub_agents', 'memory', 'multi_agent', 'human_in_the_loop', 'saga', 'event_driven'],
  },
  {
    id: 'multi_agent',
    name: 'Multi-Agent',
    category: 'agent',
    complexity: 'Advanced',
    latency: 'High',
    cost: 'High',
    bestFor: 'Enterprise systems with parallel specialization',
    requires: ['tools', 'orchestration'],
    composableWith: ['react', 'routing', 'memory'],
  },
  {
    id: 'orchestrator-worker',
    name: 'Orchestrator-Worker',
    category: 'workflow',
    complexity: 'Intermediate',
    latency: 'Medium',
    cost: 'Medium',
    bestFor: 'Complex tasks with dynamic decomposition',
    requires: [],
    composableWith: ['parallel-calls', 'evaluator-optimizer'],
  },
  {
    id: 'parallel-calls',
    name: 'Parallel Calls',
    category: 'workflow',
    complexity: 'Beginner',
    latency: 'Low',
    cost: 'Medium',
    bestFor: 'Independent sub-tasks, aggregated results',
    requires: [],
    composableWith: ['prompt-chaining', 'orchestrator-worker'],
  },
  {
    id: 'plan_and_execute',
    name: 'Plan & Execute',
    category: 'agent',
    complexity: 'Intermediate',
    latency: 'High',
    cost: 'High',
    bestFor: 'Complex multi-step tasks needing upfront planning',
    requires: ['tools'],
    composableWith: ['react', 'multi_agent'],
  },
  {
    id: 'prompt-chaining',
    name: 'Prompt Chaining',
    category: 'workflow',
    complexity: 'Beginner',
    latency: 'Medium',
    cost: 'Low',
    bestFor: 'Sequential, predictable transformations',
    requires: [],
    composableWith: ['parallel-calls', 'evaluator-optimizer'],
  },
  {
    id: 'rag',
    name: 'RAG',
    category: 'agent',
    complexity: 'Intermediate',
    latency: 'Medium',
    cost: 'Medium',
    bestFor: 'Knowledge-intensive Q&A and generation',
    requires: ['retrieval', 'vector-store'],
    composableWith: ['react', 'routing', 'reflection'],
  },
  {
    id: 'react',
    name: 'ReAct',
    category: 'agent',
    complexity: 'Intermediate',
    latency: 'Variable',
    cost: 'Medium',
    bestFor: 'Open-ended tasks requiring tool use',
    requires: ['tools'],
    composableWith: ['memory', 'reflection', 'rag'],
  },
  {
    id: 'reflection',
    name: 'Reflection',
    category: 'agent',
    complexity: 'Intermediate',
    latency: 'High',
    cost: 'High',
    bestFor: 'High-quality outputs needing self-critique',
    requires: [],
    composableWith: ['react', 'rag', 'plan_and_execute'],
  },
  {
    id: 'routing',
    name: 'Routing',
    category: 'agent',
    complexity: 'Beginner',
    latency: 'Low',
    cost: 'Low',
    bestFor: 'Multi-intent systems with specialized handlers',
    requires: [],
    composableWith: ['react', 'rag', 'multi_agent'],
  },
  {
    id: 'saga',
    name: 'Saga',
    category: 'agent',
    complexity: 'Advanced',
    latency: 'High',
    cost: 'Medium',
    bestFor: 'Long-running workflows requiring compensation on failure',
    requires: ['storage', 'idempotency', 'compensation-handlers'],
    composableWith: ['event_driven', 'multi_agent'],
  },
  {
    id: 'memory',
    name: 'Memory',
    category: 'primitive',
    complexity: 'Intermediate',
    latency: 'Medium',
    cost: 'Medium',
    bestFor: 'Sessions requiring context persistence',
    requires: ['storage'],
    composableWith: ['react', 'rag', 'multi_agent'],
  },
  {
    id: 'skills',
    name: 'Skills',
    category: 'primitive',
    complexity: 'Intermediate',
    latency: 'Low',
    cost: 'Low',
    bestFor: 'Repeatable in-context procedures the agent should perform consistently across runs',
    requires: ['skill-registry', 'trigger-matcher'],
    composableWith: ['react', 'tool_use', 'plan_and_execute', 'multi_agent', 'routing'],
  },
  {
    id: 'sub_agents',
    name: 'Sub-agents',
    category: 'primitive',
    complexity: 'Intermediate',
    latency: 'Medium',
    cost: 'Medium',
    bestFor: 'Delegating bounded sub-tasks to role-scoped agent instances',
    requires: ['role-registry', 'result-schemas', 'scoped-tools'],
    composableWith: ['multi_agent', 'plan_and_execute', 'react', 'skills', 'memory'],
  },
  {
    id: 'tool_use',
    name: 'Tool Use',
    category: 'primitive',
    complexity: 'Beginner',
    latency: 'Low',
    cost: 'Low',
    bestFor: 'Structured API calls and function execution',
    requires: ['tools'],
    composableWith: ['react', 'rag', 'routing'],
  },
  {
    id: 'guardrails',
    name: 'Guardrails',
    category: 'modifier',
    complexity: 'Advanced',
    latency: 'Medium',
    cost: 'Medium',
    bestFor: 'Layered policy checks plus a dual-LLM split against prompt injection',
    requires: ['detector-registry', 'policy-artifact', 'audit-sink'],
    composableWith: ['human_in_the_loop', 'rag', 'multi_agent', 'tool_use', 'react'],
  },
  {
    id: 'human_in_the_loop',
    name: 'Human in the Loop',
    category: 'modifier',
    complexity: 'Intermediate',
    latency: 'Variable',
    cost: 'Low',
    bestFor: 'High-stakes actions requiring human approval or correction',
    requires: ['pause-resume', 'approver-surface', 'audit'],
    composableWith: ['saga', 'event_driven', 'tool_use'],
  },
];

// ---------------------------------------------------------------------------
// Composition edges — every documented pairing between two entries with a
// 'kind' label and a one-line rationale. Sourced from
// patterns-catalog.yaml#compositions.
// ---------------------------------------------------------------------------

export type CompositionKind = 'natural' | 'useful' | 'complex' | 'redundant';

export interface CompositionEdge {
  a: string;
  b: string;
  kind: CompositionKind;
  rationale: string;
}

export const COMPOSITIONS: CompositionEdge[] = [
  { a: 'evaluator-optimizer', b: 'orchestrator-worker', kind: 'useful', rationale: 'Evaluate synthesized result' },
  { a: 'evaluator-optimizer', b: 'parallel-calls', kind: 'useful', rationale: 'Evaluate aggregated output' },
  { a: 'evaluator-optimizer', b: 'prompt-chaining', kind: 'natural', rationale: 'Evaluate chain output quality' },
  { a: 'memory', b: 'multi_agent', kind: 'natural', rationale: 'Shared agent memory' },
  { a: 'memory', b: 'plan_and_execute', kind: 'useful', rationale: 'Remember plans across sessions' },
  { a: 'memory', b: 'rag', kind: 'natural', rationale: 'Shared vector store' },
  { a: 'memory', b: 'react', kind: 'natural', rationale: 'Add session persistence' },
  { a: 'memory', b: 'reflection', kind: 'complex', rationale: 'Remember critiques' },
  { a: 'memory', b: 'routing', kind: 'useful', rationale: 'Per-route memory' },
  { a: 'memory', b: 'tool_use', kind: 'useful', rationale: 'Tools store/retrieve memory' },
  { a: 'multi_agent', b: 'plan_and_execute', kind: 'natural', rationale: 'Delegate steps to agents' },
  { a: 'multi_agent', b: 'rag', kind: 'useful', rationale: 'Agents with knowledge' },
  { a: 'multi_agent', b: 'react', kind: 'natural', rationale: 'Workers are ReAct agents' },
  { a: 'multi_agent', b: 'reflection', kind: 'useful', rationale: 'Reflect on synthesis' },
  { a: 'multi_agent', b: 'routing', kind: 'natural', rationale: 'Route to agents' },
  { a: 'multi_agent', b: 'tool_use', kind: 'natural', rationale: 'Each agent has tools' },
  { a: 'orchestrator-worker', b: 'parallel-calls', kind: 'natural', rationale: 'Workers execute in parallel' },
  { a: 'orchestrator-worker', b: 'prompt-chaining', kind: 'useful', rationale: 'Chain is the simplest form of worker' },
  { a: 'parallel-calls', b: 'prompt-chaining', kind: 'useful', rationale: 'Parallelize independent chain steps' },
  { a: 'plan_and_execute', b: 'rag', kind: 'useful', rationale: 'Retrieve context for planning' },
  { a: 'plan_and_execute', b: 'react', kind: 'natural', rationale: 'ReAct runs each plan step' },
  { a: 'plan_and_execute', b: 'reflection', kind: 'useful', rationale: 'Reflect on plan quality' },
  { a: 'plan_and_execute', b: 'routing', kind: 'complex', rationale: 'Route then plan' },
  { a: 'plan_and_execute', b: 'tool_use', kind: 'natural', rationale: 'Steps use tools' },
  { a: 'rag', b: 'react', kind: 'natural', rationale: 'Retrieve before reasoning' },
  { a: 'rag', b: 'reflection', kind: 'useful', rationale: 'Evaluate retrieval quality' },
  { a: 'rag', b: 'routing', kind: 'useful', rationale: 'RAG as one route handler' },
  { a: 'rag', b: 'tool_use', kind: 'natural', rationale: 'Retrieval as a tool' },
  { a: 'react', b: 'reflection', kind: 'useful', rationale: 'Reflect on agent output' },
  { a: 'react', b: 'routing', kind: 'useful', rationale: 'Route then run agent' },
  { a: 'react', b: 'tool_use', kind: 'natural', rationale: 'ReAct uses tool calling' },
  { a: 'reflection', b: 'routing', kind: 'complex', rationale: 'Reflect on routing' },
  { a: 'reflection', b: 'tool_use', kind: 'useful', rationale: 'Validate tool results' },
  { a: 'routing', b: 'tool_use', kind: 'useful', rationale: 'Different tools per route' },
];
